name: "[EGYM] Lint"

on:
  pull_request:
    types:
      - "synchronize"
      - "opened"

jobs:
  lint-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - uses: actions/checkout@v5
        name: Checkout Repository

      - name: Install Root dependencies
        run: npm install --ignore-scripts

      - name: Install Plugin Dependencies
        run: npm install
        working-directory: ./plugin

      - name: Using npm instead of pnpm
        run: sed -i 's/pnpm run /npm run /g' package.json
        working-directory: ./plugin

      - name: "Lint Packages"
        shell: bash
        run: npm run lint
        working-directory: ./plugin
