name: Publish Workflow

on:
  workflow_call:
    secrets:
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true

jobs:
  publish:
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
        name: Checkout Repository

      - name: Setup Environment
        uses: ./.github/actions/setup-action
        with:
          artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
          artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
  
      - name: Publish Pre-release Version
        if: ${{ github.ref_name != 'main' && github.ref_name != 'master' }}
        run: |
          npm pkg set name="@egym-private/capacitor-google-maps"
          
          # Replace pnpm with npm
          sed -i 's/pnpm run /npm run /g' package.json
          sed -i 's/pnpm downlevel-dts/npx downlevel-dts/g' package.json

          npm version "0.0.${{ github.run_number }}"
          npm version prerelease --preid="dev.${{ github.run_attempt}}"
          npm publish --tag dev --registry https://egym.jfrog.io/egym/api/npm/npm-local/
        working-directory: ./plugin