name: Development Workflow

on:
  - pull_request
  - workflow_dispatch

jobs:
  publish:
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
        name: Checkout Repository
        with:
          # TODO: check if we need to disable shallow clone
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-action
        with:
          artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
          artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Publish Pre-release Version
        if: ${{ github.ref_name != 'main' && github.ref_name != 'master' }}
        run: |
          npm pkg set name="@egym-private/capacitor-google-maps"

          npm pkg set scripts.downleveldts="npx downlevel-dts dist/typings dist/typings/ts_old --to=3.5"
          npm pkg set scripts.build="npm run clean && npm run docgen && tsc && rollup -c rollup.config.js && npm run downleveldts"
          npm pkg set scripts.prepublishOnly="npm run build"

          npm version "0.0.${{ github.run_number }}"
          npm version prerelease --preid="dev.${{ github.run_attempt}}"
          npm publish --tag dev --registry https://egym.jfrog.io/egym/api/npm/npm-local/
        working-directory: ./plugin
