name: "Release RC"

on: workflow_dispatch

permissions:
  id-token: write  # Required for OIDC for trusted publishing
  contents: write

jobs:
  setup:
    uses: ./.github/workflows/reusable_setup.yml
    secrets:
      CAP_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  lint-test:
    needs: 'setup'
    uses: ./.github/workflows/reusable_lint-packages.yml
    secrets:
      CAP_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  build-packages:
    needs: 'setup'
    uses: ./.github/workflows/reusable_build-packages.yml
    secrets:
      CAP_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  release-npm-rc:
    needs: ['build-packages', 'lint-test']
    uses: ./.github/workflows/reusable_release-npm.yml
    with:
      create-dev-release: false
      create-rc-release: true
    secrets:
      CAP_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}