name: "Verify Packages"

on: 
  workflow_call:
    secrets:
      CAP_GH_RELEASE_TOKEN:
        required: false

jobs:

  verify-ios:
    runs-on: macos-15
    timeout-minutes: 30
    strategy:
      matrix:
        xcode:
        - /Applications/Xcode_16.4.app
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN || github.token }}

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools

      - run: sudo xcode-select --switch ${{ matrix.xcode }}

      - run: pnpm run verify:ios
        working-directory: ./plugin

  verify-android:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN || github.token  }}

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      
      - run: npm run verify:android
        working-directory: ./plugin

  verify-web:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN || github.token }}

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      
      - run: npm run verify:web
        working-directory: ./plugin
